#!/usr/bin/env python3
"""
Complete guide to clean data, insert sample data, and test all reports
"""

def main():
    """Main function"""
    print("Complete Report Testing Guide")
    print("=" * 40)
    
    print("\nSTEP 1: Clean and Insert Sample Data")
    print("1. Go to Supabase Dashboard > SQL Editor")
    print("2. Copy the content from 'clean_and_insert_sample_data.sql'")
    print("3. Paste and run the script")
    print("4. Verify the summary shows all records inserted")
    
    print("\nExpected Results After Script:")
    print("- customers: 5 records")
    print("- vendors: 5 records")
    print("- projects: 5 records")
    print("- invoices: 5 records")
    print("- sales_receipts: 3 records")
    print("- bills: 5 records")
    print("- expenses: 5 records")
    print("- journal_entries: 5 records")
    print("- journal_entry_lines: 15 records")
    print("- credit_memos: 2 records")
    print("- expense_claims: 3 records")
    print("- budgets: 3 records")
    print("- budget_lines: 6 records")
    
    print("\nSTEP 2: Test All Reports")
    print("Go to your application and test these reports:")
    
    print("\n1. PROFIT & LOSS REPORT")
    print("   - Navigate to Reports > P&L Report")
    print("   - Set date range: 2024-01-01 to 2024-03-31")
    print("   - Expected results:")
    print("     * Total Revenue: ~230,000,000 VND")
    print("     * Total COGS: 0 VND (no cost of goods sold)")
    print("     * Gross Profit: ~230,000,000 VND")
    print("     * Operating Expenses: ~92,500,000 VND")
    print("     * Net Income: ~137,500,000 VND")
    print("   - Test drill-down: Click on any account line")
    
    print("\n2. BALANCE SHEET REPORT")
    print("   - Navigate to Reports > Balance Sheet")
    print("   - Set as of date: 2024-03-31")
    print("   - Expected results:")
    print("     * Assets: Cash, Bank, Accounts Receivable")
    print("     * Liabilities: Tax Payable")
    print("     * Equity: Retained Earnings")
    print("     * Total Assets = Total Liabilities + Equity")
    print("   - Test drill-down: Click on any account line")
    
    print("\n3. CASH FLOW STATEMENT")
    print("   - Navigate to Reports > Cash Flow")
    print("   - Set date range: 2024-01-01 to 2024-03-31")
    print("   - Expected results:")
    print("     * Operating Activities: Net Income adjustments")
    print("     * Investing Activities: Equipment purchases")
    print("     * Financing Activities: Capital contributions")
    print("     * Net Cash Flow: Should reconcile")
    
    print("\n4. SALES BY CUSTOMER REPORT")
    print("   - Navigate to Reports > Sales by Customer")
    print("   - Set date range: 2024-01-01 to 2024-03-31")
    print("   - Expected ranking:")
    print("     1. Tập đoàn GHI: ~88,000,000 VND")
    print("     2. Doanh nghiệp XYZ: ~60,000,000 VND")
    print("     3. Công ty TNHH ABC: ~30,000,000 VND")
    print("     4. Công ty JKL: ~16,500,000 VND")
    print("     5. Cá nhân Nguyễn C: ~6,600,000 VND")
    print("   - Test search and filter functionality")
    
    print("\n5. EXPENSES BY VENDOR REPORT")
    print("   - Navigate to Reports > Expenses by Vendor")
    print("   - Set date range: 2024-01-01 to 2024-03-31")
    print("   - Expected ranking:")
    print("     1. Tập đoàn STU: 30,000,000 VND")
    print("     2. Công ty PQR: 20,000,000 VND")
    print("     3. Nhà cung cấp MNO: 10,000,000 VND")
    print("     4. Công ty VWX: 5,000,000 VND")
    print("     5. Doanh nghiệp YZ: 8,000,000 VND")
    print("   - Test search and filter functionality")
    
    print("\n6. GENERAL LEDGER REPORT")
    print("   - Navigate to Reports > General Ledger")
    print("   - Set date range: 2024-01-01 to 2024-03-31")
    print("   - Expected results:")
    print("     * 5 journal entries in chronological order")
    print("     * 15 journal entry lines")
    print("     * Running balance calculations")
    print("     * Account codes: 111, 112, 131, 511, 3331")
    print("   - Test drill-down: Click on any transaction")
    print("   - Test filters: By account, by transaction type")
    
    print("\nSTEP 3: Test Drill-Down Functionality")
    print("For each report, test the drill-down feature:")
    print("1. Click on any summarized amount")
    print("2. Verify the drill-down modal opens")
    print("3. Check that detailed transactions are shown")
    print("4. Verify the data matches the summary")
    print("5. Test the close functionality")
    
    print("\nSTEP 4: Test Date Range Filters")
    print("For each report, test different date ranges:")
    print("1. January 2024 only")
    print("2. Q1 2024 (Jan-Mar)")
    print("3. February 2024 only")
    print("4. March 2024 only")
    print("5. Verify results change appropriately")
    
    print("\nSTEP 5: Test Search and Filter Features")
    print("For reports that have search/filter:")
    print("1. Search by customer/vendor name")
    print("2. Filter by status")
    print("3. Filter by amount ranges")
    print("4. Test pagination if applicable")
    
    print("\nSAMPLE DATA SUMMARY:")
    print("Total Sales Revenue: ~230,000,000 VND")
    print("- Invoices: ~220,000,000 VND")
    print("- Sales Receipts: ~9,800,000 VND")
    print("- Credit Memos: -6,600,000 VND")
    print("")
    print("Total Expenses: ~92,500,000 VND")
    print("- Bills: ~73,000,000 VND")
    print("- Expenses: ~19,500,000 VND")
    print("")
    print("Net Profit: ~137,500,000 VND")
    
    print("\nTROUBLESHOOTING:")
    print("If reports show no data:")
    print("1. Check date ranges are correct")
    print("2. Verify sample data was inserted")
    print("3. Check API endpoints are working")
    print("4. Verify authentication is working")
    
    print("If drill-down doesn't work:")
    print("1. Check browser console for errors")
    print("2. Verify API endpoints for drill-down")
    print("3. Check network requests in DevTools")
    
    print("\nSUCCESS CRITERIA:")
    print("✅ All 6 reports load without errors")
    print("✅ Data displays correctly in each report")
    print("✅ Drill-down functionality works")
    print("✅ Date range filters work")
    print("✅ Search and filter features work")
    print("✅ Numbers add up correctly")
    print("✅ UI is responsive and user-friendly")
    
    print("\n" + "=" * 40)
    print("Ready to test comprehensive reporting functionality!")

if __name__ == "__main__":
    main()

