"""
Script để verify code tạo project có phù hợp với database schema không
"""
import sys
import io
if sys.stdout.encoding != 'utf-8':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

print("=" * 100)
print("KIỂM TRA TÍNH TƯƠNG THÍCH GIỮA CODE VÀ DATABASE SCHEMA")
print("=" * 100)
print()

# Database Schema (từ MCP query)
db_columns = {
    'id': {'type': 'uuid', 'nullable': False, 'default': 'uuid_generate_v4()'},
    'project_code': {'type': 'varchar(50)', 'nullable': False},
    'name': {'type': 'varchar(255)', 'nullable': False},
    'description': {'type': 'text', 'nullable': True},
    'customer_id': {'type': 'uuid', 'nullable': True, 'fk': 'customers(id)'},
    'manager_id': {'type': 'uuid', 'nullable': True, 'fk': 'employees(id)'},
    'start_date': {'type': 'date', 'nullable': False},
    'end_date': {'type': 'date', 'nullable': True},
    'budget': {'type': 'numeric', 'nullable': True},
    'actual_cost': {'type': 'numeric', 'nullable': True, 'default': '0'},
    'status': {'type': 'project_status enum', 'nullable': True, 'default': "'planning'"},
    'status_id': {'type': 'uuid', 'nullable': True, 'fk': 'project_statuses(id)'},
    'priority': {'type': 'project_priority enum', 'nullable': True, 'default': "'medium'"},
    'progress': {'type': 'numeric', 'nullable': True, 'default': '0.0'},
    'billing_type': {'type': 'varchar(20)', 'nullable': True, 'default': "'fixed'"},
    'hourly_rate': {'type': 'numeric', 'nullable': True},
    'category_id': {'type': 'uuid', 'nullable': True, 'fk': 'project_categories(id)'},
    'created_at': {'type': 'timestamp with time zone', 'nullable': True, 'default': 'now()'},
    'updated_at': {'type': 'timestamp with time zone', 'nullable': True, 'default': 'now()'},
}

# Code fields (từ ProjectCreate model và create_project endpoint)
code_fields = {
    'id': 'Generated by backend (uuid.uuid4())',
    'project_code': 'From ProjectCreate model (required)',
    'name': 'From ProjectCreate model (required)',
    'description': 'From ProjectCreate model (optional)',
    'customer_id': 'From ProjectCreate model (optional, validated)',
    'manager_id': 'From ProjectCreate model (optional, validated)',
    'start_date': 'From ProjectCreate model (required, converted to ISO string)',
    'end_date': 'From ProjectCreate model (optional, converted to ISO string)',
    'budget': 'From ProjectCreate model (optional)',
    'actual_cost': 'From ProjectCreate model (optional, default 0.0)',
    'status': 'From ProjectCreate model (optional, default planning, removed if status_id exists)',
    'status_id': 'From ProjectCreate model (optional, validated)',
    'priority': 'From ProjectCreate model (default medium, converted enum to string)',
    'progress': 'From ProjectCreate model (default 0.0)',
    'billing_type': 'From ProjectCreate model (default fixed)',
    'hourly_rate': 'From ProjectCreate model (optional)',
    'category_id': 'From ProjectCreate model (optional, validated)',
    'created_at': 'Generated by backend (datetime.utcnow().isoformat())',
    'updated_at': 'Generated by backend (datetime.utcnow().isoformat())',
}

print("SO SÁNH DATABASE SCHEMA VỚI CODE:")
print("-" * 100)
print()

# Check if all DB columns are handled in code
print("1. KIỂM TRA TẤT CẢ COLUMNS TRONG DATABASE ĐƯỢC XỬ LÝ:")
print()
all_match = True
for db_col, db_info in db_columns.items():
    if db_col in code_fields:
        status = "✅"
    else:
        status = "❌ MISSING"
        all_match = False
    
    nullable = "NULL" if db_info['nullable'] else "NOT NULL"
    fk_info = f" (FK: {db_info.get('fk', 'N/A')})" if db_info.get('fk') else ""
    default_info = f" (default: {db_info.get('default', 'N/A')})" if db_info.get('default') else ""
    
    print(f"  {status} {db_col:20s} | {db_info['type']:25s} | {nullable:10s}{fk_info}{default_info}")

print()
print("2. KIỂM TRA CODE KHÔNG CÓ FIELD THỪA:")
print()
code_has_extra = False
for code_col in code_fields.keys():
    if code_col not in db_columns:
        print(f"  ⚠️  {code_col}: Có trong code nhưng không có trong database (sẽ bị filter bởi valid_columns)")
        code_has_extra = True

if not code_has_extra:
    print("  ✅ Không có field thừa")

print()
print("3. KIỂM TRA REQUIRED FIELDS:")
print()
required_fields = ['id', 'project_code', 'name', 'start_date']
for field in required_fields:
    db_info = db_columns.get(field, {})
    code_info = code_fields.get(field, '')
    
    if not db_info.get('nullable', True) and field in code_fields:
        print(f"  ✅ {field}: Required trong DB, có trong code")
    elif not db_info.get('nullable', True):
        print(f"  ❌ {field}: Required trong DB, THIẾU trong code")
        all_match = False

print()
print("4. KIỂM TRA FOREIGN KEY VALIDATION:")
print()
fk_fields = ['customer_id', 'manager_id', 'category_id', 'status_id']
for fk_field in fk_fields:
    if fk_field in db_columns and db_columns[fk_field].get('fk'):
        if 'validated' in code_fields.get(fk_field, ''):
            print(f"  ✅ {fk_field}: Có validation trong code")
        else:
            print(f"  ⚠️  {fk_field}: Có FK constraint nhưng chưa có validation trong code")

print()
print("5. KIỂM TRA ENUM HANDLING:")
print()
enum_fields = ['status', 'priority']
for enum_field in enum_fields:
    db_info = db_columns.get(enum_field, {})
    if 'enum' in db_info.get('type', '').lower():
        if 'converted' in code_fields.get(enum_field, '').lower() or 'removed' in code_fields.get(enum_field, '').lower():
            print(f"  ✅ {enum_field}: Enum được xử lý đúng (convert to string hoặc remove)")
        else:
            print(f"  ⚠️  {enum_field}: Enum có thể cần xử lý")

print()
print("=" * 100)
if all_match and not code_has_extra:
    print("✅ KẾT LUẬN: Code phù hợp với database schema")
else:
    print("⚠️  KẾT LUẬN: Có một số vấn đề cần xử lý")
print("=" * 100)
